{
 "title": "CAMS",
 "time": { "from": "2024-07-22T00:10:00.000Z", "to": "2024-08-20T00:10:00.000Z" },
 "templating": {
  "list": [
   { "name": "webhook_url", "label": "URL", "query": "https://example.com/webhook1" },
   {
    "name": "webhook_id",
    "query": "SELECT webhook_id from webhook_details where webhook_url = '${webhook_url}'"
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "gauge",
   "description": "Tells the current callback url health",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT health FROM webhook_analytics where webhook_id = '${webhook_id}' "
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "description": "Percentage of time the webhook returned a success response in last 30 days",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT success_rate FROM webhook_analytics WHERE webhook_id = '${webhook_id}'"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "stat",
   "description": "Avg latency experienced by the webhook for last 30 days",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg_latency FROM webhook_analytics WHERE webhook_id = '${webhook_id}'"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "stat",
   "description": "Total no of events received for the webhook in last 30 days",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT total_events FROM webhook_analytics WHERE webhook_id = '${webhook_id}'"
    }
   ]
  },
  {
   "title": "Total Retries",
   "type": "stat",
   "description": "Total no fo retry attempts for a particular webhook",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT retry_count FROM webhook_analytics WHERE webhook_id = '${webhook_id}'"
    }
   ]
  },
  {
   "title": " Performance: Latency vs. TPM",
   "type": "timeseries",
   "description": "Last 30 days",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('1 minute', timestamp) AS time,\n  EXTRACT(EPOCH FROM avg(latency)) * 1000 AS avg_latency_ms\nFROM\n  webhook_events\nWHERE\n  webhook_id = '${webhook_id}'\n  AND timestamp >= now() - interval '30 days'\nGROUP BY time\nORDER BY time;\n"
    },
    {
     "rawSql": "SELECT\n  time_bucket('1 minute', timestamp) AS time,\n  count(*) AS tpm\nFROM\n  webhook_events\nWHERE\n  webhook_id = 'webhook_1'\n  AND timestamp >= now() - interval '30 days'  -- Ensure you're looking at the last 30 days\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  }
 ]
}